apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coursebench
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=reg.geekpie.club/proxy/shanghaitechgeekpie/coursebench-next
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
spec:
  project: coursebench
  source:
    repoURL: https://github.com/ShanghaitechGeekPie/coursebench-next.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: coursebench
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jqPathExpressions:
        - .spec.bootstrap.initdb.encoding
        - .spec.bootstrap.initdb.localeCType
        - .spec.bootstrap.initdb.localeCollate
        - .spec.enablePDB
        - .spec.enableSuperuserAccess
        - .spec.failoverDelay
        - .spec.logLevel
        - .spec.maxSyncReplicas
        - .spec.minSyncReplicas
        - .spec.monitoring
        - .spec.postgresGID
        - .spec.postgresUID
        - .spec.primaryUpdateMethod
        - .spec.primaryUpdateStrategy
        - .spec.replicationSlots
        - .spec.resources.limits.cpu
        - .spec.smartShutdownTimeout
        - .spec.startDelay
        - .spec.stopDelay
        - .spec.switchoverDelay
        - .spec.postgresql.parameters
        - .spec.postgresql.syncReplicaElectionConstraint
        - .spec.storage.resizeInUseVolumes
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
